config/routes.rb
Rails.application.routes.draw do
 
  get 'dashboard/index'
  devise_for :users
  root 'dashboard#index'

	# get 'assign_project_to_developer', to: 'projects#assign_project_to_developer'
	# get  'add_developer' ,to: 'projects#add_developer'
	# get 'take_bug_developer', to: 'bugs#take_bug_developer'
	get 'assign_bug_developer', to: 'bugs#assign_bug_developer'
	get 'assign_status_to_project', to: 'bugs#assign_status_to_project'
	get 'remove_bug_developer', to: 'bugs#remove_bug_developer'
	# get 'new_form', to: 'projects#new_form'
	# get 'new_bug', to: 'bugs#new_bug'


  shallow do
  	resources :projects do
			member do
				get 'bugs'
				get 'assign_project_to_developer'
				get 'add_developer'
				get 'remove_developer'
			end	
			resources :bugs
				member do
					get 'assignment_bug_developer'
					# get 'assign_bug_developer'
					# get 'assign_bug_developer'
			end
			get 'assignment_try'
		end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ApplicationRecord
  belongs_to :project

  has_one_attached :image
  validates :title, presence: true,uniqueness: true ,
                    length: { minimum: 5}

  validate :image_type                  

  has_many :users ,through: :usersprojects

  enum type:[:Bug,:Feature]
	enum projectstatus:[:New,:Started,:Completed]

	scope:image_check , -> {where("image <> '' ")}

	def image_type
		if image.attached? && !image.content_type.in?(%w(image/jpeg image/png))
			errors.add(:image, 'Must be a jgeg pr png')
		end
	end
end

app/models/bug_developer.rb
class BugDeveloper < ApplicationRecord
	belongs_to :user
	belongs_to :project
	belongs_to :bugs
end

app/models/project.rb
class Project < ApplicationRecord
  validates_associated :bugs
	validates :title, presence: true,uniqueness: true ,
                    length: { minimum: 5}

	scope :check_developer, -> {joins(:usersprojects).where(:user_id, current_user.id)}

  belongs_to :user
  has_many :usersprojects, dependent: :destroy

  # has_many :bug_developers, dependent: :destroy
  # has_many :bugs ,through: :bug_developers

  has_many :bugs, dependent: :destroy
  has_many :users, through: :usersprojects

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :projects

  has_many :bugs 
  # has_many :bug_developers, dependent: :destroy

  has_many :usersprojects, dependent: :destroy
  has_many :projects, through: :usersprojects
  enum user_type: [:projectmanager, :qa, :developer]

  # validates :email,
  # format: { with: /^(.+)@(.+)$/, message: "Email invalid"  },
  #           uniqueness: { case_sensitive: false },
  #           length: { minimum: 4, maximum: 254 } 
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/
end

app/models/usersproject.rb
class Usersproject < ApplicationRecord
	belongs_to :user
	belongs_to :project

	scope :check, -> {where("user_id =?", current_user.id)}

	# scope :serch_developers, -> {joins(:comments).merge(Comment.null_comment_check)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit
		protect_from_forgery
	# before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?
	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :user_type])
		devise_parameter_sanitizer.permit(:bug, keys: [:type, :projectstatus])

	end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  respond_to :html, :xml

  before_action :configure_permitted_parameters, if: :devise_controller?
  

	def create
    	@project = Project.find(params[:project_id])
    	@bug = @project.bugs.create(bug_params)
      @bug.update(creator_bug_id: current_user.id)

    if @project.save
      flash.now[:notice] = "We have exactly books available."
      redirect_to project_path(@project)
    else

      render 'new'
    end

  end

 	def destroy
    	@bug = Bug.find(params[:id])
    	@bug.destroy
    	redirect_to project_url(@bug.project_id)
  end

  def assign_bug_developer
    @project = Project.find(params[:project_id])
    @bug = Bug.find(params[:bug_id])
    @bug.update(user_bug_id: current_user.id)
    @bug.update(project_bug_status: 'started')
    render 'assignment_bug_developer'

  end

  def remove_bug_developer
    @project = Project.find(params[:project_id])

    @bug = Bug.find(params[:bug_id])
    @bug.update(user_bug_id: nil)
    @bug.update(project_bug_status: 'new') 
    render 'assignment_bug_developer'
  end

  def assign_status_to_project
    @project = Project.find(params[:project_id])
    @bug = Bug.find(params[:bug_id])
    @bug.update(project_bug_status: 'completed')
    redirect_to project_path(@project)

  end

  def edit

  end

  def update

  end

  def show
    @project = Project.find(params[:project_id])
    @bug = Bug.find(params[:id])
    render 'assignment_bug_developer'
  end
  # def project_assignment_try
  #    @project = Project.find(params[:project_id])
  #   @bug = Bug.find(params[:id])
  #   render 'assignment_bug_developer'
  # end

  # def assignment_bug_developer
  #   @project = Project.find(params[:project_id])
  #   @bug = Bug.find(params[:id])
  #   render 'assignment_bug_developer'
  # end


  private
    def bug_params
      params.require(:bug).permit(:title, :body, :image,:bug_type,:project_bug_status,:deadline)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :authenticate_user! , except: [:show , :index]
	respond_to :html, :xml
	# after_action :verify_authorized, except: :index
	# after_action :verify_policy_scoped, only: :index 
	def index
    @projects = Project.all
  end

	def new
		  @project = Project.new
		  authorize @project
		  respond_with @projects
  end


  def add_developer
  
  	@user = User.find(params[:user_id])
  	@users = User.where(user_type: :developer)
  	@project = Project.find(params[:id])
  	@project.users<< @user
  	render 'assign_project_to_developer'
  end

  def  remove_developer
  
  	@user = User.find(params[:user_id])
  	@users = User.where(user_type: :developer)
  	@project = Project.find(params[:id])
  	userproject = Usersproject.find_by(user_id: @user.id, project_id: @project.id)
    userproject.destroy if userproject
    render 'assign_project_to_developer'

  end

  def assign_project_to_developer
  	
		@users = User.where(user_type: :developer)
		@project = Project.find(params[:id])
    render 'assign_project_to_developer'
	end

  def create
  	@project = Project.new(project_params)
  	authorize @project
  	@project.user= current_user

  	if @project.save
    	redirect_to @project
  	else
    	render 'new'
  	end
  end
  def new_form

  end
	def show
    @project = Project.find(params[:id])
    respond_with @projects
  end
  def edit
  	@project = Project.find(params[:id])
  	respond_with @projects
	end

	def update
  	@project = Project.find(params[:id])
  	authorize @project
  	if @project.update(project_params)
    	redirect_to @project
  	else
    	render 'edit'
  	end
	end


	def destroy
    @project = Project.find(params[:id])
    @project.destroy
 
    redirect_to projects_path
  end

	private
	def set_project
		@project = Project.find(params[:id])
		authorize @project

	end
  def project_params
    params.require(:project).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	
end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/bugs/_bug.html.erb
<html lang="en">
<head>
<title>Page Title</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.grid-container {
  display: grid;
  grid-template-columns: auto auto auto auto;
  grid-gap: 0px;
  background-color: white;

}

.grid-container > div {
  text-align: center;
  padding: 0px 0;
  font-size: 16px;
  margin-right: 10px
}
.grid-container2 {
  display: grid;
  grid-template-columns: auto auto auto auto;
  grid-gap: 0px;
  background-color: white;
  padding: 10px;
}
.grid-container2 > div {
  text-align: center;
  padding: 5px 0;
  font-size: 16px;
  table-layout: fixed;
  width: 40px;
  margin-left: 70px;
}
 .item1 {
  font-size: 22px; 
  grid-row: 1;
}
.item2 a{
  color: black; 
}
 .item2 {
  font-size: 16px; 
  grid-row: 1;
}
.grid-container h2{

  color: #683181 ;
}
.functions h1{
  color: #683181;
  font-size: 30px; 

  text-align: center;
}
.button5 {
  background-color: #008CBA;
  text-align: center;

    left: 45%;
    margin: 0;
  position: absolute;

}
hr{

  margin-left:  50px;
  margin-right: 50px ;
}
.button2 {background-color: #4CAF50;}
.button4 {background-color: #f44336;} /* Red */ 
.button3 {background-color: #e7e7e7; color: black;} /* Gray */ 
</style>
</head>
</html>


<hr>
<div class="grid-container2">
  <div class="item2">
   
      <%= bug.title%>
    
  </div>   
  <div class="item2">
  
      <%= bug.body%>
    
  </div>
  <div class="item2">
    <% if bug.image.present?%>
      <div style = "width:100px; height:70px">
        <%= link_to image_tag(bug.image, style: 'width:100%', padding: '200px', margin: '10px'),projects_path %>
      </div>
      <%else %>
        <p>
          <strong>No Attachment found</strong>
        </p>
    <% end %>
  </div>
   <div class="item2">
    <p>
      <%= bug.bug_type%>
    </p>
  </div>
  <div class="item2">
    <p>
      <%= bug.project_bug_status%>
    </p>
  </div>

  <div class="item2">
    <p>
    <%if policy(bug).dev? || policy(@project).qa? %>
        <button class="button2">
          <%= link_to 'Show', bug_path(bug,project_id: @project.id) %>
        </button>
        <%if policy(@project).qa? && bug.creator_bug_id== current_user.id%>
          <button class="button4">
            <%= link_to 'delete',  bug,
                     method: :delete,
                     data: { confirm: 'Are you sure?' } %>
          </button>
        <%end %>
    <% end %>
    </p>
  </div>

  <div class="item2">

    <%if (policy(@project).pm? || policy(bug).dev?) && current_user.id == bug.user_bug_id && bug.project_bug_status!='completed'%>
      <p> Taken By id:"<%= bug.user_bug_id %>"</p>
    <%elsif bug.project_bug_status=='completed'%>
      <p> Completed By id:"<%= bug.user_bug_id %>"</p>
    <%elsif (policy(@project).pm? || policy(bug).dev?) && bug.user_bug_id%>
    <p> Taken </p>
    <% end %>
  </div>

</div>

app/views/bugs/_form.html.erb
  

<%= form_with(model: [ @project, @project.bugs.build ],:authenticity_token => true ,local: true) do |form| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <%= csrf_meta_tags %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, required: true,minlength: 4%>
  </p>
  <p>
    <%= form.label :description%><br>
    <%= form.text_area :body%>
  </p>

  <p>
    <%= form.label :image%><br>
    <%= form.file_field :image%>
  </p>
    
  <div class = "field">
    <%= form.label :deadline %>
    <%= form.text_field :deadline, id: :project_deadline%>
  </div>  

  <div class="field">
    <% bug_type=['Bug','Feature'] %>
    <%= form.label :bugtype %>
    <%= form.select :bug_type, bug_type, {}, id: :bug_type ,onchange: "getoption()" %>
  </div>

  <script>

  function getoption() {
    var options=[ ['New','Started','Resolved'],['New','Started','Completed']];
    var x= document.getElementById("bug_type").selectedIndex;
    var i;
    var option="";
    for(i =0;i<options[x].length;i++)
    {
      option += '<option value ="'+options[x][i]+'"'+'>'+options[x][i]+'</option>';
    }
    document.getElementById("project_bug_status").innerHTML=option;
  }

  $('document').ready(function(){
    $('#project_deadline').datepicker({
        dateFormat: 'yy-mm-dd'
    });
  }); 

  </script>

  <div class="field">
    <%= form.label :project_bug_status %>
    <%= form.select(:project_bug_status,['New','Started','Completed'], {},id: :project_bug_status) %>
  </div>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/bugs/assign.html.erb
<!-- 
<p>
  <strong>Title:</strong>
  <%= @bug.title%>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @bug.body%>
</p>

<% if @bug.image.present?%>
  <div style = "width:100px; height:70px">
    <strong>Attachment: </strong>
    <%= link_to image_tag(@bug.image, style: 'width:100%', padding: '200px', margin: '10px'),projects_path %>
  </div>
  <%else %>
    <p>
      <strong>No Attachment found</strong>
    </p>
<% end %>

<p></p>

<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script>
  $(document).ready(function () {
    $("#formButton").click(function(){
      $("#form1").toggle();
      });
  });
</script>

<%if policy(@bug).dev? %>
  <%if current_user.id == @bug.user_bug_id %>
    <%= link_to 'Remove Bug Assignment', remove_bug_developer_path(bug_id: @bug.id, project_id: @project.id)  %>
  <%else%>
    <%= link_to 'Take Bug', assign_bug_developer_path(bug_id: @bug.id, project_id: @project.id)  %>
  <% end %>
<% end %>

<%if policy(@project).qa? %>
<p>
  <%= link_to 'Delete', @bug,
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
<% end %>
 -->

app/views/bugs/assignment_bug_developer.html.erb
<p>
  <strong>Title:</strong>
  <%= @bug.title%>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @bug.body%>
</p>

<% if @bug.image.present?%>
  <div style = "width:100px; height:70px">
    <strong>Attachment: </strong>
    <%= link_to image_tag(@bug.image, style: 'width:100%', padding: '200px', margin: '10px'),projects_path %>
  </div>
  <%else %>
    <p>
      <strong>No Attachment found</strong>
    </p>
<% end %>
<p></p>
<p>
  <strong>Bug Status:</strong>
  <%= @bug.project_bug_status%>
</p>
<p>
  <strong>Bug Deadline:</strong>
  <%= @bug.deadline %>
</p>
<p></p>
<%if policy(@bug).dev? %>
  <%if current_user.id == @bug.user_bug_id %>
    <%= link_to 'Remove Bug Assignment', remove_bug_developer_path(bug_id: @bug.id, project_id: @project.id)  %>
    <p></p>
    <%= link_to 'Mark as Complete', assign_status_to_project_path(bug_id: @bug.id, project_id: @project.id) %>

  <%else%>
    <%= link_to 'Take Bug', assign_bug_developer_path(bug_id: @bug.id, project_id: @project.id)  %>
  <% end %>
<% end %>

<%if policy(@project).qa? && @bug.creator_bug_id==current_user.id%>
<p>
  <%= link_to 'Delete', @bug,
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
<% end %>
<p></p>



<P></P>
<%= link_to 'Back', project_path(@project) %>

app/views/bugs/new.html.erb
<%= render 'form' %>

app/views/projects/assign_project_to_developer.html.erb
<html lang="en">
<head>
<title>Page Title</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<body>

<style >
  
  .add_color a{

    color: black;
  }
</style>
<div class="header2">
  <h1>Test Project</h1>
  <p>By Muneeb</p>
</div>

<div class="header">
  <% if current_user %>
    <%= link_to 'Home', dashboard_index_path %>
    <%= link_to 'Account', edit_user_registration_path  %>
    <%= link_to 'Sign Out',destroy_user_session_path , method: :delete %>
  <% else %>
    <%= link_to "Sign In     " , new_user_session_path  %>
    <%= link_to ' Sign Up', new_user_registration_path  %>
  <%end %>
</div>

</head>

</body>
</html>


<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Userid</th>

    <th></th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.user_type %></td>
      <div class="add_color">
        <%if user == @project.users.find_by(id: user.id) %> 
          <td><%= link_to 'Remove Developer', remove_developer_project_path(@project.id,user_id: user.id)  %></td>
        <%else%>
          <td><%= link_to 'Add Developer', add_developer_project_path(@project.id,user_id: user.id)  %></td>
        <%end %>
      </div> 
    </tr>
  <% end %>
</table>
</body>
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<html lang="en">
<head>
<title>Page Title</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<style>
.grid-container {
  display: grid;
  grid-template-columns: auto auto auto auto;
  grid-gap: 0px;

  background-color: white;

}

.grid-container > div {
  text-align: center;
  padding: 0px 0;
  width: 190px;
  font-size: 16px;
  margin-left: 170px
}
.grid-container2 {
  display: grid;
  grid-template-columns: auto auto auto auto;
  grid-gap: 0px;
  background-color: white;
  padding: 10px;
}
.grid-container2 > div {
  text-align: center;
  padding: 5px 0;
  font-size: 16px;
  table-layout: fixed;
  width: 190px;
      margin-left: 170px;

}
 .item1 {
  font-size: 22px; 
  grid-row: 1;
}
.item2 a{
  color: black; 
}
 .item2 {
  font-size: 16px; 
  grid-row: 1;
}
.grid-container h2{

  color: #683181 ;
}
.functions h1{
  color: #683181;
  font-size: 30px; 

  text-align: center;
}
.button5 {
  background-color: #008CBA;
  text-align: center;

    left: 45%;
    margin: 0;
    border-radius: 12px;
}
.button5 a{
  color:black;
}
hr{

  margin-left:  50px;
  margin-right: 50px ;
}
.button2 {background-color: #4CAF50;border-radius: 12px;}
.button4 {background-color: #f44336;border-radius: 12px;} /* Red */ 
.button3 {background-color: #e7e7e7; color: black;border-radius: 12px;} /* Gray */ 
</style>

<body>

<div class="header2">
  <h1>Bugzilla</h1>
  <p>By Muneeb</p>
</div>

<div class="header">
  <% if current_user %>
    <%= link_to 'Home', dashboard_index_path %>
    <%= link_to 'Account', edit_user_registration_path  %>
    <%= link_to 'Sign Out',destroy_user_session_path , method: :delete %>
  <% else %>
    <%= link_to "Sign In     ." , new_user_session_path  %>
    <%= link_to ' Sign Up', new_user_registration_path  %>

  <%end %>
</div>

</head>

</body>
</html>

<div class="functions">
  <%if current_user && current_user.projectmanager? %>
    <p> You are signed in as project manager </p>
  <% elsif current_user && current_user.qa? %>
    <p> You are signed in as QA </p>
  <%elsif current_user && current_user.developer? %>
    <p> You are signed in as developer </p>
  <%end %>
  <h1>All Projects</h1>
</div>
<div class="grid-container">
  <div class="item1"><h2>Title </h2></div>
  <div class="item1"><h2>text</h2></div>
  <div class="item1"><h2>Action </h2></div>

</div> 
<p></p>

<% @projects.each do |project| %>
<% if policy(project).qa? || policy(project).pm? %>
  <hr>
<%end %>
  <div class="grid-container2">
    <% if policy(project).qa? || policy(project).pm? %>

      <div class="item2">
          <p><%= project.title %></p>

      </div>

      <div class="item2">
          <p><%= project.body %></p>

      </div>
  
      <div class="item2">
        <p>
        <button class="button2">
          <%= link_to 'Show', project_path(project) %>
        </button>
        <%if current_user && current_user.projectmanager? && project.user_id == current_user.id %>
          <button class="button3">
            <%= link_to 'Edit', edit_project_path(project) %>
          </button>
          <button class="button4">
            <%= link_to 'Destroy', project_path(project),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %>
          </button>
        </p> 
        <%end %>
      </div>    

    <%elsif policy(project).dev? %>
      <% if project == current_user.projects.find_by(id: project.id)%>
        <div class="item2">
          <%= project.title %>
        </div>
        <div class="item2">
          <%= project.body %>
        </div>
      
        <div class="item2">
          <button class="button2">
            <%= link_to 'Show', project_path(project) %>
          </button>
        </div>
      <% end %>   
    <%end %>
  </div>  
<% end %>

<hr>
<%if policy(@projects).create? %>
   <button class="button5">
    <%= link_to 'Add New project', new_project_path %>
  </button>
<%end %>

app/views/projects/new.html.erb
<html lang="en">
<head>
<title>Page Title</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- <style>
/* Style the body */
body {
  font-family: Arial;
  margin: 0;
}

/* Header/Logo Title */
/* Header/Logo Title */
.header {
	margin-top: -20px;
  padding: 10px;
  padding-right: 100px; 
  text-align: right;
  background:#683181;
  color: white;
  font-size: 30px;
}
.header a{
  color: white;
}

a:link {
	color:black;

}
.header2 {
	margin-top: -30px;
	text-align: left;
  padding: 10px;
  background:     #683181    ;
  color: white;
  color
  font-size: 30px;
}
.button {
  text-align: center;
  background-color: #683181;
  border: 1px;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  width: 130px;
   margin: 0;
  position: absolute;
  top: 30%;
  left: 50%;
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
}
.button a{
  color: white;

}
</style> -->
<body>

<div class="header2">
  <h1>Bugzilla</h1>
  <p>By Muneeb</p>
</div>

<div class="header">
  <% if current_user %>
    <%= link_to 'Home', dashboard_index_path %>
    <%= link_to 'Account', edit_user_registration_path  %>
		<%= link_to 'Sign Out',destroy_user_session_path , method: :delete %>
	<% else %>
		<%= link_to "Sign In     ." , new_user_session_path  %>
    <%= link_to ' Sign Up', new_user_registration_path  %>

	<%end %>
</div>

</head>

</body>
</html>


<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<html lang="en">
<head>
<title>Page Title</title>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="sNMk592JV2wwHn6DPJ8C5oy/hHDnjIlZBOHyngtTbpQ=" />
<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script>
	$(document).ready(function () {
		$("#formButton").click(function(){
	    $("#form1").toggle();
	    });
	});
</script>
<style>
	
	 .item1 {
	 	margin-left: -30px;
  font-size: 18px; 
  grid-row: 1;
}
.functions h3{

  color: #683181;
  font-size: 20px; 

  text-align: center;
}

.item1 h3
{
	font-size: 20px;
	color: #683181;
}
hr{

   margin-left: 50px;
  margin-right:50px ;
}
.button2 {background-color: #4CAF50;  border-radius: 12px;
}
.button4 {background-color: #f44336;  border-radius: 12px;
} /* Red */ 
.button3 {background-color: #e7e7e7; color: black;  border-radius: 12px;
} /* Gray */ 
</style>

<body>

<div class="header2">
  <h1>Bugzilla</h1>
  <p>By Muneeb</p>
</div>

<div class="header">
  <% if current_user %>
    <%= link_to 'Home', dashboard_index_path %>
    <%= link_to 'Account', edit_user_registration_path  %>
		<%= link_to 'Sign Out',destroy_user_session_path , method: :delete %>
	<% else %>
		<%= link_to "Sign In     ." , new_user_session_path  %>
    <%= link_to ' Sign Up', new_user_registration_path  %>
	<%end %>
</div>


<h4>
  <strong>Title:</strong>
  <%= @project.title %>
</h4>
 
<h4>
  <strong>Text:</strong>
  <%= @project.body %>
</h4>
<h4>
  <strong>User:</strong>
 	 <%= @project.user.email.split('@')[0].capitalize %>
</h4>
<p> </p>
<%if current_user && current_user.projectmanager? && @project.user_id == current_user.id %>
	<div class="item4">
		<%if policy(@project).create? %>
			<p>
      <button class="button2">
				<%= link_to 'click to add developers', assign_project_to_developer_project_path(@project.id) %>
			</button>	

       <button class="button3">
	      <%= link_to 'Edit Project', edit_project_path(@project) %>
			</button>
      <button class="button4">
	      <%= link_to 'Destroy', project_path(@project),
	              method: :delete,
	              data: { confirm: 'Are you sure?' } %>
	    </button>
	    </p>  
	  <% end %>
	</div> 
<% end %>

<div class= functions>
	<h1>Bugs</h1>
</div>
<% if @project.bugs %>
	<% if @project.bugs.present? %>

	  <div class="grid-container">
	    <div class="item1"><h3>Title </h3></div>
	    <div class="item1"><h3>Description</h3></div>
	    <div class="item1"><h3>Image</h3></div>
	    <div class="item1"><h3>Bug type</h3></div>
	    <div class="item1"><h3>Bug Status</h3></div>
	    <div class="item1"><h3>Action</h3></div>
	    <div class="item1"><h3>Assigned to</h3></div>

	  </div>
	  <%= render @project.bugs%>
	<% else %>
			<div class="grid-container">
    		<div class="item2"><h4>No bugs found for this project </h4></div>
  		</div>
	<%end%>
<%end %> 

<% if current_user && current_user.qa? %>
	<h1> Want to Add a Bug ? </h1>
			<%= render 'bugs/form'%>

<%end %>

<p> </p>
<%= link_to 'Back', projects_path %>
</head>

</body>
</html>